name: 'Terraform Deployment with Confirmation and Region as Variable'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      region:
        description: 'AWS Region to deploy'
        required: true
        type: choice
        options:
          - us-east-1
          - us-east-2
      confirm_apply:
        description: 'Do you want to apply the changes? (yes or no)'
        required: true
        type: choice
        options:
          - yes
          - no

jobs:
  terraform:
    name: 'Terraform Apply with Confirmation and Region as Variable'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: |
          echo "Initializing Terraform for environment: ${{ github.event.inputs.environment }} in region: ${{ github.event.inputs.region }}"
          terraform init -backend-config="bucket=terraform-state-${{ github.event.inputs.environment }}" \
                         -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate" \
                         -backend-config="region=${{ github.event.inputs.region }}"
        env:
          TF_LOG: ERROR

      - name: Plan Terraform
        run: |
          echo "Planning Terraform for environment: ${{ github.event.inputs.environment }} in region: ${{ github.event.inputs.region }}"
          terraform plan -var="environment=${{ github.event.inputs.environment }}" \
                         -var="region=${{ github.event.inputs.region }}" \
                         -var-file=environments/${{ github.event.inputs.environment }}/variables.tfvars
        env:
          TF_LOG: ERROR
        continue-on-error: false

      - name: User Confirmation Check
        if: ${{ github.event.inputs.confirm_apply != 'yes' }}
        run: |
          echo "You chose not to apply the changes. Exiting the workflow."
          exit 0

      - name: Apply Terraform
        if: ${{ github.event.inputs.confirm_apply == 'yes' }}
        run: |
          echo "Applying Terraform changes to environment: ${{ github.event.inputs.environment }} in region: ${{ github.event.inputs.region }}"
          terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}" \
                          -var="region=${{ github.event.inputs.region }}" \
                          -var-file=environments/${{ github.event.inputs.environment }}/variables.tfvars
        env:
          TF_LOG: ERROR
        continue-on-error: false

      - name: Completion Message
        if: ${{ success() }}
        run: |
          echo "Terraform deployment completed successfully for environment: ${{ github.event.inputs.environment }} in region: ${{ github.event.inputs.region }} 🎉"

      - name: Error Message
        if: ${{ failure() }}
        run: |
          echo "An error occurred during the Terraform deployment for environment: ${{ github.event.inputs.environment }} in region: ${{ github.event.inputs.region }} ❌"
          exit 1

